### ISSUE TITLE
Error: Cannot find module 'cypress-cucumber-preprocessor' - localhost, docker

### ISSUE THREAD

**Issue by rootsher** [TheBrainFamily/cypress-cucumber-preprocessor#642]
### Current behavior

Error:

`Error: Cannot find module 'cypress-cucumber-preprocessor'`

```
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/e2e/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/root/.cache/Cypress/8.7.0/Cypress/resources/app/packages/server/lib/errors.js:1035:15)
    at EventEmitter.<anonymous> (/root/.cache/Cypress/8.7.0/Cypress/resources/app/packages/server/lib/plugins/index.js:174:21)
    at EventEmitter.emit (events.js:376:20)
    at ChildProcess.<anonymous> (/root/.cache/Cypress/8.7.0/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:376:20)
    at emit (internal/child_process.js:910:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

### Desired behavior

I have two services in docker-compose - `admin` and `admin-cypress`. In `admin` I keep tests and installed `cypress-cucumber-preprocessor`. Whereas `admin-cypress` is an image `cypress/included:8.7.0` which has a mounted volume with tests.

When starting Cypress, I get an error that it cannot see the `cypress-cucumber-preprocessor` package - even though it is installed.

### Test code to reproduce

Configuration (docker-compose):

```
admin-cypress:
  image: cypress/included:8.7.0
  depends_on:
    - admin
  environment:
    - DISPLAY
    - HTTP_PROXY=gateway
  working_dir: /e2e
  entrypoint: cypress open --project /e2e
  volumes:
    - ./apps/admin/test/e2e:/e2e:cached
    - /tmp/.X11-unix:/tmp/.X11-unix
```

Configuration (cypress.json):
```
{
  "baseUrl": "http://admin.localhost",
  "integrationFolder": "integration",
  "pluginsFile": "plugins/index.js",
  "supportFile": "support/index.js",
  "fixturesFolder": "fixtures",
  "screenshotsFolder": "screenshots",
  "videosFolder": "videos",
  "testFiles": "**/*.feature"
}
```

Configuration (package.json):
```
"cypress-cucumber-preprocessor": "^4.3.0",
....
"cypress-cucumber-preprocessor": {
  "nonGlobalStepDefinitions": true
}
```

### Versions

* **Cypress version**: `cypress/included:8.7.0`
* **Preprocessor version**: `4.3.0`
* **Node version**: `14.17.0` (from image `cypress/included:8.7.0`)

**Comment by rootsher** [comment]
Solved... `cypress-cucumber-preprocessor` should be inside `cypress/included` - so you must mount node_modules as volume into it.

```
admin-cypress:
  image: cypress/included:8.7.0
  depends_on:
    - admin
  environment:
    - DISPLAY
    - HTTP_PROXY=gateway
  working_dir: /e2e
  entrypoint: cypress open --project /e2e
  volumes:
    - ./apps/admin/test/e2e:/e2e:cached
    - ./apps/admin/node_modules:/e2e/node_modules:cached # <--- WORKS
    - /tmp/.X11-unix:/tmp/.X11-unix

**Comment by rootsher** [comment]
Possibly add `cypress-cucumber-preprocessor` installation to the image (maybe Cypress Team (@chrisbreiding ?) would agree to add this package...).

**Comment by rootsher** [comment]
Volume mapping was not needed - I removed the package from the project and below is the solution to extend the base image.

I extended the base `cypress/included` and use my own `Dockerfile`:
```
FROM cypress/included:8.7.0

WORKDIR /e2e

RUN npm init --yes
RUN npm install --save-dev cypress-cucumber-preprocessor

VOLUME /e2e/node_modules

ENTRYPOINT cypress run --project /e2e
```

and `docker-compose.yml`:
```
admin-cypress:
  build:
    context: docker/admin/cypress
  depends_on:
    - admin
  environment:
    - DISPLAY
    - HTTP_PROXY=gateway
  volumes:
    - ./apps/admin/test/e2e:/e2e:cached
    - /tmp/.X11-unix:/tmp/.X11-unix
```
